### ISSUE TITLE
Migrate to monorepo setup for Opla project

### ISSUE THREAD

**Issue by mikbry** [Opla/opla#1]
### See
Yarn Workspaces
https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

https://hackernoon.com/one-vs-many-why-we-moved-from-multiple-git-repos-to-a-monorepo-and-how-we-set-it-up-f4abb0cfe469

**Comment by licarth** [comment]
## Benefits 
**saves precious development time**
- avoid `.circleci/config.yaml` duplication.
- make PR / changes easier and easier to test (proper e2e testing)
- easier management of certificates, and allows wildcard certificates in an easy-ish way.
- de-duplicates ingress.yaml
- de-duplicates README.md
- makes dev onboarding simpler
- removes the necessity for an infra branch in opla/opla.

**makes the app easier to install for users/admins**
- allows a single point of entry for someone who wants to deploy opla as an application (who wants only the backend or only the front)

### Risks
1 commit for 2 releases. Beware of downtime due to api changes. Every change should be retrocompatible with the previous version(s).
--> good news is that we could automate that testing against version n-1 and/or n-2 of the backend or of the frontend if this becomes a problem, since we have a single repo.

### What is it to do 
- [ ] merge code from `Opla/backend`, `Opla/front` and `Opla/opla (infra branch)`
- [ ] adapt `.circleci/config.yaml` (very 
-

**Comment by licarth** [comment]
A point on history : 
The tricky point is not about moving the code into a single repo, but is about moving the code into subfoldlers (`front/` and `backend/`)

- Commits and SHAs will not get lost and stay the same :
`https://github.com/Opla/backend/commit/d3ea8cb1e159a57823df791dd62323649d5df080`
becomes `https://github.com/Opla/opla/commit/d3ea8cb1e159a57823df791dd62323649d5df080`.
- Rollback to a point before the merging of the repos will no longer be possible. (which is an argument for doing it early)
- Clicking on History will only show history since the repo merge. This is because github executes `git log` instead of `git log --follow`. Gitlab does use `--follow`. (see https://github.com/isaacs/github/issues/900)

**Short term github workaround** : a [chrome extension](https://chrome.google.com/webstore/detail/github-follow/agalokjhnhheienloigiaoohgmjdpned) allows to add an easy link to the history before the file got renamed. Try it yourself with [`backend/package.json`](https://github.com/Opla/opla/commits/singlerepo/backend/package.json)
![image](https://user-images.githubusercontent.com/5550241/44260235-1464dc00-a214-11e8-8b09-f6bc671d4252.png)

**Locally** just run `git log --follow <file>` instead of `git log <file>` to get the complete history. To have it at all times : `git config log.follow true`

**Long term fix** : [upvote this issue](https://github.com/isaacs/github/issues/900).

**Comment by mikbry** [comment]
Add docker setup and add in /README how to install it

**Comment by licarth** [comment]
@mikbry Docker like docker-compose (what's in community edition) or docker kubernetes ?

**Comment by mikbry** [comment]
docker-compose

**Comment by licarth** [comment]
This is done in #18.
